/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Login;
import java.sql.Connection;
import java.sql.Date;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author ricar
 */
public class Buscador extends javax.swing.JDialog {
    public static final String url="jdbc:mysql://localhost:3306/proyectoadministracion?autoReconnet=true&useSSL=false";
    public static final String usuario="root";
    public static final String Constrase="Ricardo";
        PreparedStatement ps;
    ResultSet rs;
     public com.mysql.jdbc.Connection getConnection()
      {
         com.mysql.jdbc.Connection conexion=null;
         try{
             Class.forName("com.mysql.jdbc.Driver");
             conexion=(com.mysql.jdbc.Connection) DriverManager.getConnection(url,usuario,Constrase);
           //  JOptionPane.showMessageDialog(null,"Conexion Existosa");
         }catch(Exception ex)
         {
             System.out.println("error  "+ex);
         }
         return conexion;
      }
    /**
     * Creates new form Buscador
     */
    public Buscador(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        this.setLocation(900, 20);
        initComponents();
    }
    private void llenardatos()
    {
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        etiquetaclave = new javax.swing.JLabel();
        eiquetaproducto = new javax.swing.JLabel();
        cajaproducto = new javax.swing.JTextField();
        etiquetacantidad = new javax.swing.JLabel();
        etiquetacosto = new javax.swing.JLabel();
        etiquetacaducidad = new javax.swing.JLabel();
        cajacantidad = new javax.swing.JTextField();
        cajacosto = new javax.swing.JTextField();
        caja_fechacompra = new javax.swing.JTextField();
        etiquetabuscador = new javax.swing.JLabel();
        cajaclave = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        boton_buscar2 = new javax.swing.JButton();
        caja_fechacaducidad = new javax.swing.JTextField();
        idproducto = new javax.swing.JTextField();
        boton_modificar = new javax.swing.JButton();
        boton_eliminar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(153, 102, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        etiquetaclave.setBackground(new java.awt.Color(0, 0, 0));
        etiquetaclave.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        etiquetaclave.setForeground(new java.awt.Color(255, 255, 255));
        etiquetaclave.setText("Clave:");
        jPanel1.add(etiquetaclave, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, -1, 20));

        eiquetaproducto.setBackground(new java.awt.Color(0, 0, 0));
        eiquetaproducto.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        eiquetaproducto.setForeground(new java.awt.Color(255, 255, 255));
        eiquetaproducto.setText("Producto:");
        jPanel1.add(eiquetaproducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        cajaproducto.setBackground(new java.awt.Color(0, 0, 0));
        cajaproducto.setForeground(new java.awt.Color(255, 255, 255));
        cajaproducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cajaproductoActionPerformed(evt);
            }
        });
        jPanel1.add(cajaproducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, 100, 30));

        etiquetacantidad.setBackground(new java.awt.Color(0, 0, 0));
        etiquetacantidad.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        etiquetacantidad.setForeground(new java.awt.Color(255, 255, 255));
        etiquetacantidad.setText("Cantidad:");
        jPanel1.add(etiquetacantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, -1));

        etiquetacosto.setBackground(new java.awt.Color(0, 0, 0));
        etiquetacosto.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        etiquetacosto.setForeground(new java.awt.Color(255, 255, 255));
        etiquetacosto.setText("Costo:");
        jPanel1.add(etiquetacosto, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, -1, -1));

        etiquetacaducidad.setBackground(new java.awt.Color(0, 0, 0));
        etiquetacaducidad.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        etiquetacaducidad.setForeground(new java.awt.Color(255, 255, 255));
        etiquetacaducidad.setText("Fecha de compra:");
        jPanel1.add(etiquetacaducidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 60, -1, -1));

        cajacantidad.setBackground(new java.awt.Color(0, 0, 0));
        cajacantidad.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(cajacantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, 100, 30));

        cajacosto.setBackground(new java.awt.Color(0, 0, 0));
        cajacosto.setForeground(new java.awt.Color(255, 255, 255));
        cajacosto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cajacostoActionPerformed(evt);
            }
        });
        jPanel1.add(cajacosto, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, 100, 30));

        caja_fechacompra.setBackground(new java.awt.Color(0, 0, 0));
        caja_fechacompra.setForeground(new java.awt.Color(255, 255, 255));
        caja_fechacompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caja_fechacompraActionPerformed(evt);
            }
        });
        jPanel1.add(caja_fechacompra, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 50, 110, 30));

        etiquetabuscador.setBackground(new java.awt.Color(0, 0, 0));
        etiquetabuscador.setFont(new java.awt.Font("Arial", 3, 24)); // NOI18N
        etiquetabuscador.setForeground(new java.awt.Color(255, 255, 255));
        etiquetabuscador.setText("Buscador");
        jPanel1.add(etiquetabuscador, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, -1, -1));

        cajaclave.setBackground(new java.awt.Color(0, 0, 0));
        cajaclave.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        cajaclave.setForeground(new java.awt.Color(255, 255, 255));
        cajaclave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cajaclaveActionPerformed(evt);
            }
        });
        jPanel1.add(cajaclave, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, 100, 30));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Fecha de caducidad:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 160, -1, -1));

        boton_buscar2.setBackground(new java.awt.Color(0, 0, 0));
        boton_buscar2.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        boton_buscar2.setForeground(new java.awt.Color(255, 255, 255));
        boton_buscar2.setText("Buscar");
        boton_buscar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_buscar2ActionPerformed(evt);
            }
        });
        jPanel1.add(boton_buscar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(321, 280, 110, -1));

        caja_fechacaducidad.setBackground(new java.awt.Color(0, 0, 0));
        caja_fechacaducidad.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(caja_fechacaducidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 150, 110, 30));

        idproducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idproductoActionPerformed(evt);
            }
        });
        jPanel1.add(idproducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 0, 80, -1));

        boton_modificar.setBackground(new java.awt.Color(0, 0, 0));
        boton_modificar.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        boton_modificar.setForeground(new java.awt.Color(255, 255, 255));
        boton_modificar.setText("Modificar");
        boton_modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_modificarActionPerformed(evt);
            }
        });
        jPanel1.add(boton_modificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 280, 110, -1));

        boton_eliminar.setBackground(new java.awt.Color(0, 0, 0));
        boton_eliminar.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        boton_eliminar.setForeground(new java.awt.Color(255, 255, 255));
        boton_eliminar.setText("Eliminar");
        boton_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_eliminarActionPerformed(evt);
            }
        });
        jPanel1.add(boton_eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, 110, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 475, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 351, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cajaproductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cajaproductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cajaproductoActionPerformed

    private void cajacostoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cajacostoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cajacostoActionPerformed

    private void caja_fechacompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caja_fechacompraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_caja_fechacompraActionPerformed

    private void cajaclaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cajaclaveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cajaclaveActionPerformed

    private void boton_buscar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_buscar2ActionPerformed
        // TODO add your handling code here:
        Connection conexion=null;
        try{
            conexion=getConnection();
            ps=conexion.prepareStatement("select *from Producto where clave=? ");
            ps.setString(1,cajaclave.getText());
                  rs=ps.executeQuery();
                  if(rs.next())
                  {   idproducto.setText(String.valueOf(rs.getInt("id_producto")));
                      cajaclave.setText(String.valueOf(rs.getInt("clave")));
                      cajaproducto.setText(rs.getString("nombre"));
                      cajacantidad.setText(String.valueOf(rs.getInt("cantidad")));
                      cajacosto.setText(String.valueOf(rs.getFloat("costo")));
                      caja_fechacompra.setText(String.valueOf(rs.getDate("fecha_de_compra")));
                      caja_fechacaducidad.setText(String.valueOf(rs.getDate("fecha_de_caducidad")));
                  }
                  else
                  {
                      JOptionPane.showMessageDialog(null,"No existe la clave que ingreso");
                  }
                  conexion.close();
        }catch(Exception ex)
        {
            System.err.println("Error , "+ex);
        }
      
    }//GEN-LAST:event_boton_buscar2ActionPerformed
    public void limpiarcajas()
    {
        cajaclave.setText(null);
        cajaproducto.setText(null);
        cajacantidad.setText(null);
        cajacosto.setText(null);
        caja_fechacompra.setText(null);
        caja_fechacaducidad.setText(null);
   }
    private void boton_modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_modificarActionPerformed
        // TODO add your handling code here:
        Connection conexion= null;
                try{
                    
                    conexion=getConnection();
                    ps=conexion.prepareStatement("UPDATE  Producto set clave=? ,nombre=?,cantidad=?,costo=? ,fecha_de_compra=?,fecha_de_caducidad=? where id_producto=?");
                   ps.setString(1,cajaclave.getText());
                   ps.setString(2,cajaproducto.getText());
                   ps.setString(3,cajacantidad.getText());
                   ps.setString(4,cajacosto.getText());
                   ps.setDate(5,Date.valueOf(caja_fechacompra.getText()));
                   ps.setDate(6,Date.valueOf(caja_fechacaducidad.getText()));
                   ps.setInt(7,Integer.parseInt(idproducto.getText()));
                   int resultado=ps.executeUpdate();
                   if(resultado>0)
                   {
                       JOptionPane.showMessageDialog(null,"Registro modificado con existo");
                       limpiarcajas();
                   }
                   else
                       
                   {
                       JOptionPane.showMessageDialog(null,"Error al modificar el registro");
                       limpiarcajas();
                   }
                   conexion.close();
                }catch(Exception ex){
                System.err.println("Error  ,"+ex);        
               }
                
        
        
    }//GEN-LAST:event_boton_modificarActionPerformed

    private void idproductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idproductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idproductoActionPerformed

    private void boton_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_eliminarActionPerformed
        // TODO add your handling code here:
           Connection conexion= null;
                try{
                    
                    conexion=getConnection();
                    ps=conexion.prepareStatement("delete from Producto where id_producto=?");
                   
                   ps.setInt(1,Integer.parseInt(idproducto.getText()));
                   int resultado=ps.executeUpdate();
                   if(resultado>0)
                   {
                       JOptionPane.showMessageDialog(null,"Registro fue eliminado con exito");
                       limpiarcajas();
                   }
                   else
                       
                   {
                       JOptionPane.showMessageDialog(null,"Error al elimiar registro");
                       limpiarcajas();
                   }
                   conexion.close();
                }catch(Exception ex){
                System.err.println("Error  ,"+ex);        
               }
    }//GEN-LAST:event_boton_eliminarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Buscador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Buscador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Buscador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Buscador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Buscador dialog = new Buscador(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boton_buscar2;
    private javax.swing.JButton boton_eliminar;
    private javax.swing.JButton boton_modificar;
    private javax.swing.JTextField caja_fechacaducidad;
    public javax.swing.JTextField caja_fechacompra;
    public javax.swing.JTextField cajacantidad;
    public javax.swing.JTextField cajaclave;
    public javax.swing.JTextField cajacosto;
    public javax.swing.JTextField cajaproducto;
    private javax.swing.JLabel eiquetaproducto;
    private javax.swing.JLabel etiquetabuscador;
    private javax.swing.JLabel etiquetacaducidad;
    private javax.swing.JLabel etiquetacantidad;
    private javax.swing.JLabel etiquetaclave;
    private javax.swing.JLabel etiquetacosto;
    private javax.swing.JTextField idproducto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
