/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Login;
import com.mysql.jdbc.Connection;
import static Login.Login.Constrase;
import static Login.Login.url;
import static Login.Login.usuario;
import com.mysql.jdbc.Connection;
import java.sql.Date;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ricar
 */
public class inventarioo extends javax.swing.JFrame {
    DefaultTableModel modelo= new DefaultTableModel();
     Buscador buscar=new Buscador(this,true);
     DefaultComboBoxModel <ventanainventario> modelo2=new DefaultComboBoxModel <ventanainventario> ();
    /**
     * Creates new form inventarioo
     */
      public static final String url="jdbc:mysql://localhost:3306/proyectoadministracion?autoReconnet=true&useSSL=false";
    public static final String usuario="root";
    public static final String Constrase="Ricardo";
    
    PreparedStatement ps;
    ResultSet rs;
  
    
    
    public inventarioo() {
        
        initComponents();
        this.setLocationRelativeTo(null);
        llenarcombobox();
        this.idiproducto.setVisible(false);
        modelo.addColumn("Clave");
         modelo.addColumn("Producto");
          modelo.addColumn("Cantidad");
           modelo.addColumn("Costo");
            modelo.addColumn("Caducidad");
            this.tablainventario.setModel(modelo);
           
    }
        public Connection getConnection()
      {
         Connection conexion=null;
         try{
             Class.forName("com.mysql.jdbc.Driver");
             conexion=(Connection) DriverManager.getConnection(url,usuario,Constrase);
           //  JOptionPane.showMessageDialog(null,"Conexion Existosa");
         }catch(Exception ex)
         {
             System.out.println("error  "+ex);
         }
         return conexion;
      }
    
    private void  llenarcombobox()
    {
        modelo2.addElement(new ventanainventario("1", "madera","45", "28.9 pz", "15/28/20"));
        modelo2.addElement(new ventanainventario("2", "Palstico","45", "28.9 pz", "15/28/20"));
        modelo2.addElement(new ventanainventario("3", "metal","45", "28.9 pz", "15/28/20"));
        modelo2.addElement(new ventanainventario("4", "nada","45", "28.9 pz", "15/28/20"));
        modelo2.addElement(new ventanainventario("5", "nirvana","45", "28.9 pz", "15/28/20"));
        modelo2.addElement(new ventanainventario("6", "fuchi","45", "28.9 pz", "15/28/20"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelinventario = new javax.swing.JPanel();
        etiquetainventario = new javax.swing.JLabel();
        etiquetaclave = new javax.swing.JLabel();
        etiquetaproducto = new javax.swing.JLabel();
        etiquetacantidad = new javax.swing.JLabel();
        etiquetacosto = new javax.swing.JLabel();
        cajaclave = new javax.swing.JTextField();
        cajaproducto = new javax.swing.JTextField();
        cajacantidad = new javax.swing.JTextField();
        cajacosto = new javax.swing.JTextField();
        botonagregar = new javax.swing.JButton();
        botonnuevo = new javax.swing.JButton();
        botoneliminar = new javax.swing.JButton();
        botoneliminartodo = new javax.swing.JButton();
        botonsalir = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablainventario = new javax.swing.JTable();
        botonbuscar = new javax.swing.JButton();
        et_fechacaducidad = new javax.swing.JLabel();
        idiproducto = new javax.swing.JTextField();
        et_fechacompra = new javax.swing.JLabel();
        caja_fechacompra = new javax.swing.JTextField();
        caja_fechacaducidad = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        panelinventario.setBackground(new java.awt.Color(0, 102, 102));
        panelinventario.setForeground(new java.awt.Color(255, 255, 255));
        panelinventario.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        etiquetainventario.setBackground(new java.awt.Color(0, 0, 0));
        etiquetainventario.setFont(new java.awt.Font("Arial", 3, 36)); // NOI18N
        etiquetainventario.setForeground(new java.awt.Color(255, 255, 255));
        etiquetainventario.setText("Inventario");
        panelinventario.add(etiquetainventario, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, -1, 60));

        etiquetaclave.setBackground(new java.awt.Color(0, 0, 0));
        etiquetaclave.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        etiquetaclave.setForeground(new java.awt.Color(255, 255, 255));
        etiquetaclave.setText("Clave:");
        panelinventario.add(etiquetaclave, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, -1, 20));

        etiquetaproducto.setBackground(new java.awt.Color(0, 0, 0));
        etiquetaproducto.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        etiquetaproducto.setForeground(new java.awt.Color(255, 255, 255));
        etiquetaproducto.setText("Producto:");
        panelinventario.add(etiquetaproducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 100, -1, -1));

        etiquetacantidad.setBackground(new java.awt.Color(0, 0, 0));
        etiquetacantidad.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        etiquetacantidad.setForeground(new java.awt.Color(255, 255, 255));
        etiquetacantidad.setText("Cantidad:");
        panelinventario.add(etiquetacantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 150, -1, -1));

        etiquetacosto.setBackground(new java.awt.Color(0, 0, 0));
        etiquetacosto.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        etiquetacosto.setForeground(new java.awt.Color(255, 255, 255));
        etiquetacosto.setText("Costo:");
        panelinventario.add(etiquetacosto, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 190, -1, -1));

        cajaclave.setBackground(new java.awt.Color(0, 0, 0));
        cajaclave.setForeground(new java.awt.Color(255, 255, 255));
        panelinventario.add(cajaclave, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, 110, 30));

        cajaproducto.setBackground(new java.awt.Color(0, 0, 0));
        cajaproducto.setForeground(new java.awt.Color(255, 255, 255));
        panelinventario.add(cajaproducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 90, 110, 30));

        cajacantidad.setBackground(new java.awt.Color(0, 0, 0));
        cajacantidad.setForeground(new java.awt.Color(255, 255, 255));
        panelinventario.add(cajacantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 140, 110, 30));

        cajacosto.setBackground(new java.awt.Color(0, 0, 0));
        cajacosto.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        cajacosto.setForeground(new java.awt.Color(255, 255, 255));
        panelinventario.add(cajacosto, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 180, 110, 30));

        botonagregar.setBackground(new java.awt.Color(0, 0, 0));
        botonagregar.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        botonagregar.setForeground(new java.awt.Color(255, 255, 255));
        botonagregar.setText("Agregar");
        botonagregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonagregarActionPerformed(evt);
            }
        });
        panelinventario.add(botonagregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, -1, -1));

        botonnuevo.setBackground(new java.awt.Color(0, 0, 0));
        botonnuevo.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        botonnuevo.setForeground(new java.awt.Color(255, 255, 255));
        botonnuevo.setText("Limpiar");
        botonnuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonnuevoActionPerformed(evt);
            }
        });
        panelinventario.add(botonnuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 250, -1, -1));

        botoneliminar.setBackground(new java.awt.Color(0, 0, 0));
        botoneliminar.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        botoneliminar.setForeground(new java.awt.Color(255, 255, 255));
        botoneliminar.setText("Eliminar");
        botoneliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botoneliminarActionPerformed(evt);
            }
        });
        panelinventario.add(botoneliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 250, -1, -1));

        botoneliminartodo.setBackground(new java.awt.Color(0, 0, 0));
        botoneliminartodo.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        botoneliminartodo.setForeground(new java.awt.Color(255, 255, 255));
        botoneliminartodo.setText("Eliiminar Todo");
        botoneliminartodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botoneliminartodoActionPerformed(evt);
            }
        });
        panelinventario.add(botoneliminartodo, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 250, -1, -1));

        botonsalir.setBackground(new java.awt.Color(0, 0, 0));
        botonsalir.setForeground(new java.awt.Color(255, 255, 255));
        botonsalir.setText("Salir");
        botonsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonsalirActionPerformed(evt);
            }
        });
        panelinventario.add(botonsalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 10, -1, -1));

        tablainventario.setBackground(new java.awt.Color(0, 102, 102));
        tablainventario.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tablainventario.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        tablainventario.setForeground(new java.awt.Color(255, 255, 255));
        tablainventario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablainventario);

        panelinventario.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 560, 160));

        botonbuscar.setBackground(new java.awt.Color(0, 0, 0));
        botonbuscar.setForeground(new java.awt.Color(255, 255, 255));
        botonbuscar.setText("Buscar");
        botonbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonbuscarActionPerformed(evt);
            }
        });
        panelinventario.add(botonbuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 250, 80, -1));

        et_fechacaducidad.setBackground(new java.awt.Color(0, 0, 0));
        et_fechacaducidad.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        et_fechacaducidad.setForeground(new java.awt.Color(255, 255, 255));
        et_fechacaducidad.setText("Fecha de caducidad:");
        panelinventario.add(et_fechacaducidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, -1, -1));

        idiproducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idiproductoActionPerformed(evt);
            }
        });
        panelinventario.add(idiproducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 110, -1));

        et_fechacompra.setBackground(new java.awt.Color(0, 0, 0));
        et_fechacompra.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        et_fechacompra.setForeground(new java.awt.Color(255, 255, 255));
        et_fechacompra.setText("Fecha de compra:");
        panelinventario.add(et_fechacompra, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));

        caja_fechacompra.setBackground(new java.awt.Color(0, 0, 0));
        caja_fechacompra.setForeground(new java.awt.Color(255, 255, 255));
        panelinventario.add(caja_fechacompra, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, 110, 30));

        caja_fechacaducidad.setBackground(new java.awt.Color(0, 0, 0));
        caja_fechacaducidad.setForeground(new java.awt.Color(255, 255, 255));
        caja_fechacaducidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caja_fechacaducidadActionPerformed(evt);
            }
        });
        panelinventario.add(caja_fechacaducidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 184, 110, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelinventario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelinventario, javax.swing.GroupLayout.PREFERRED_SIZE, 468, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonsalirActionPerformed
        // TODO add your handling code here:
        Login lg=new Login();
        
        this.dispose();
        lg.setVisible(true);
    }//GEN-LAST:event_botonsalirActionPerformed

    private void botonagregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonagregarActionPerformed
        // TODO add your handling code here:
        String [] agregar=new String [6];
        agregar[0]=cajaclave.getText();
        agregar[1]=cajaproducto.getText();
        agregar[2]=cajacantidad.getText();
        agregar[3]=cajacosto.getText();
        agregar[4]=caja_fechacompra.getText();
        agregar[5]=caja_fechacaducidad.getText();
        modelo.addRow(agregar);
        
        Connection conexion= null;
                try{
                    
                    conexion=getConnection();
                    ps=conexion.prepareStatement("insert into Producto(clave,nombre,cantidad,costo,fecha_de_compra,fecha_de_caducidad)values(?,?,?,?,?,?)");
                   ps.setString(1,cajaclave.getText());
                   ps.setString(2,cajaproducto.getText());
                   ps.setString(3,cajacantidad.getText());
                   ps.setString(4,cajacosto.getText());
                   ps.setDate(5,Date.valueOf(caja_fechacompra.getText()));
                   ps.setDate(6,Date.valueOf(caja_fechacaducidad.getText()));
                   int resultado=ps.executeUpdate();
                   if(resultado>0)
                   {
                       JOptionPane.showMessageDialog(null,"Registro agregado con existo");
                       limpiarcajas();
                   }
                   else
                       
                   {
                       JOptionPane.showMessageDialog(null,"Error al agregar el registro");
                       limpiarcajas();
                   }
                   conexion.close();
                }catch(Exception ex){
                System.err.println("Error  ,"+ex);        
               }
                
    
        
    }//GEN-LAST:event_botonagregarActionPerformed

    private void botonnuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonnuevoActionPerformed
        // TODO add your handling code here:
         limpiarcajas(); 
        
    }//GEN-LAST:event_botonnuevoActionPerformed

    private void botoneliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botoneliminarActionPerformed
        // TODO add your handling code here:
        int eliminar=tablainventario.getSelectedRowCount();
        if(eliminar>=0){
            modelo.removeRow(eliminar);
        }
        else 
            
        {
            JOptionPane.showMessageDialog(null,"No hay datos ");
        }
    }//GEN-LAST:event_botoneliminarActionPerformed

    private void botoneliminartodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botoneliminartodoActionPerformed
        // TODO add your handling code here:
        int eliminartodo=tablainventario.getRowCount();
        for(int n=eliminartodo-1; n>=0; n--)
        {
            modelo.removeRow(n);
        }


    }//GEN-LAST:event_botoneliminartodoActionPerformed

    private void botonbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonbuscarActionPerformed
        // TODO add your handling code here:
        
        //ventanainventario vi=(ventanainventario)combobuscar.getSelectedItem();
        /*
        String clave=vi.getClave();
        String producto=vi.getProducto();
        String cantidad=vi.getCantidad();
        String costo=vi.getCosto();
        String caducidad=vi.getCaducidad();
        
       buscar.cajaclave.setText(clave);
       buscar.cajaproducto.setText(producto);
       buscar.cajacantidad.setText(cantidad);
       buscar.cajacosto.setText(costo);
       buscar.caja_fechacompra.setText(ccaducidad);
      // buscar.cajaclave.setEditable();
          buscar.cajaproducto.setEditable(false);
             buscar.cajacantidad.setEditable(false);
                buscar.cajacosto.setEditable(false);
                   buscar.caja_fechacompra.setEditable(false);*/
      buscar.setVisible(true);
      
        
    }//GEN-LAST:event_botonbuscarActionPerformed
    public  void limpiarcajas()
    {
        cajaclave.setText(null);
        cajaproducto.setText(null);
        cajacantidad.setText(null);
        cajacosto.setText(null);
        caja_fechacompra.setText(null);
        caja_fechacaducidad.setText(null);
    }
    private void idiproductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idiproductoActionPerformed
        
    }//GEN-LAST:event_idiproductoActionPerformed

    private void caja_fechacaducidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caja_fechacaducidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_caja_fechacaducidadActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(inventarioo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(inventarioo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(inventarioo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(inventarioo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new inventarioo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonagregar;
    private javax.swing.JButton botonbuscar;
    private javax.swing.JButton botoneliminar;
    private javax.swing.JButton botoneliminartodo;
    private javax.swing.JButton botonnuevo;
    private javax.swing.JButton botonsalir;
    private javax.swing.JTextField caja_fechacaducidad;
    private javax.swing.JTextField caja_fechacompra;
    private javax.swing.JTextField cajacantidad;
    private javax.swing.JTextField cajaclave;
    private javax.swing.JTextField cajacosto;
    private javax.swing.JTextField cajaproducto;
    private javax.swing.JLabel et_fechacaducidad;
    private javax.swing.JLabel et_fechacompra;
    private javax.swing.JLabel etiquetacantidad;
    private javax.swing.JLabel etiquetaclave;
    private javax.swing.JLabel etiquetacosto;
    private javax.swing.JLabel etiquetainventario;
    private javax.swing.JLabel etiquetaproducto;
    private javax.swing.JTextField idiproducto;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panelinventario;
    private javax.swing.JTable tablainventario;
    // End of variables declaration//GEN-END:variables
}
