/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Login;

import static Login.nuevos_usuarios.ns2;
import com.mysql.jdbc.Connection;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.showInputDialog;

/**
 *
 * @author ricar
 */
public class Login extends javax.swing.JFrame implements ActionListener {
     
    inventarioo inve=new inventarioo();
    
   public static final String url="jdbc:mysql://localhost:3306/Diseño?autoReconnet=true&useSSL=false";
    public static final String usuario="root";
    public static final String Constrase="Ricardo";
   
    
    /**
     * Creates new form Login
     */
    
    public Login() {
        
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JPanel();
        boton = new javax.swing.JButton();
        imagenusuario = new javax.swing.JLabel();
        etiquetausuario = new javax.swing.JLabel();
        etiquetaconstraseña = new javax.swing.JLabel();
        cajausuario = new javax.swing.JTextField();
        cajaconstraseña = new javax.swing.JPasswordField();
        botoniniciar = new javax.swing.JButton();
        etiquetalogin = new javax.swing.JLabel();
        botonnuevousuario = new javax.swing.JButton();
        conector = new javax.swing.JButton();
        imagenfondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        boton.setBackground(new java.awt.Color(0, 0, 0));
        boton.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        boton.setForeground(new java.awt.Color(255, 255, 255));
        boton.setText("Salir");
        boton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonActionPerformed(evt);
            }
        });
        panel.add(boton, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 20, 90, -1));
        boton.getAccessibleContext().setAccessibleParent(this);

        imagenusuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/us2m.png"))); // NOI18N
        imagenusuario.setText("jLabel1");
        panel.add(imagenusuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 60, 124, 150));

        etiquetausuario.setBackground(new java.awt.Color(51, 51, 51));
        etiquetausuario.setFont(new java.awt.Font("Arial", 3, 24)); // NOI18N
        etiquetausuario.setForeground(new java.awt.Color(255, 255, 255));
        etiquetausuario.setText("Usuario:");
        panel.add(etiquetausuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 240, -1, -1));

        etiquetaconstraseña.setBackground(new java.awt.Color(0, 0, 0));
        etiquetaconstraseña.setFont(new java.awt.Font("Arial", 3, 24)); // NOI18N
        etiquetaconstraseña.setForeground(new java.awt.Color(255, 255, 255));
        etiquetaconstraseña.setText("Constraseña:");
        panel.add(etiquetaconstraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 160, -1));

        cajausuario.setBackground(new java.awt.Color(0, 0, 0));
        cajausuario.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        cajausuario.setForeground(new java.awt.Color(255, 255, 255));
        panel.add(cajausuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 240, 490, -1));

        cajaconstraseña.setBackground(new java.awt.Color(0, 0, 0));
        cajaconstraseña.setFont(new java.awt.Font("Arial", 3, 24)); // NOI18N
        cajaconstraseña.setForeground(new java.awt.Color(255, 255, 255));
        panel.add(cajaconstraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 290, 490, 30));

        botoniniciar.setBackground(new java.awt.Color(0, 0, 0));
        botoniniciar.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        botoniniciar.setForeground(new java.awt.Color(255, 255, 255));
        botoniniciar.setText("Iniciar Sención");
        botoniniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botoniniciarActionPerformed(evt);
            }
        });
        panel.add(botoniniciar, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 340, 200, -1));

        etiquetalogin.setBackground(new java.awt.Color(0, 0, 0));
        etiquetalogin.setFont(new java.awt.Font("Arial", 3, 24)); // NOI18N
        etiquetalogin.setForeground(new java.awt.Color(255, 255, 255));
        etiquetalogin.setText("Login");
        panel.add(etiquetalogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 200, 80, -1));

        botonnuevousuario.setBackground(new java.awt.Color(0, 0, 0));
        botonnuevousuario.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        botonnuevousuario.setForeground(new java.awt.Color(255, 255, 255));
        botonnuevousuario.setText("crear nuevo usuario");
        botonnuevousuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonnuevousuarioActionPerformed(evt);
            }
        });
        panel.add(botonnuevousuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        conector.setBackground(new java.awt.Color(0, 0, 0));
        conector.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        conector.setForeground(new java.awt.Color(255, 255, 255));
        conector.setText("Conectar Base de Datos");
        conector.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                conectorActionPerformed(evt);
            }
        });
        panel.add(conector, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 340, -1, -1));

        imagenfondo.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        imagenfondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/imagenfondo.png"))); // NOI18N
        panel.add(imagenfondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 710, 410));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_botonActionPerformed

    private void botoniniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botoniniciarActionPerformed
        // TODO add your handling code here:
         nuevos_usuarios nss= new nuevos_usuarios(this,true);
         
         String usuarionuevo=ns2.getNombre();
         String constraseñanuevousuario=ns2.getConstraseña();
        String usuariocorrecto="R";
        String constraseñacorrecta="A";
        
        if(usuariocorrecto.equals(cajausuario.getText()) || usuarionuevo.equals(cajausuario.getText() ))
        {
            String constraseña="";
            for(int n=0;n< cajaconstraseña.getPassword().length; n++)
            {
                constraseña+=cajaconstraseña.getPassword()[n];
             
            }
            if(constraseñacorrecta.equals(constraseña) || constraseñanuevousuario.equals(constraseña))
             {
                // JOptionPane.showMessageDialog(null,"Ingresaste wiii");
                 /*if(constraseñanuevousuario.equals(constraseña) && usuarionuevo.equals(cajausuario.getText()))
                 { 
                     this.dispose();
                     JOptionPane.showMessageDialog(null,"Bienvenido\n"+
                             ns2.getNombre()+"  "+ns2.getApellido()+
                             " \n"+ns2.getCorreo()+"\n"+
                             ns2.getTelefono());
                 }*/
                 
                 inve.setVisible(true);
                 
                 this.dispose();
                 
             }
             else 
             {
                 JOptionPane.showMessageDialog(null,"Constraseña Incorrecta");
                 
             }
        }
        else
        {
            JOptionPane.showMessageDialog(null,"Este usuario no existe");
        }
    }//GEN-LAST:event_botoniniciarActionPerformed

    private void botonnuevousuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonnuevousuarioActionPerformed
        // TODO add your handling code here:
        int constraseña=12345;
        int usu=0;
        usu=Integer.parseInt(JOptionPane.showInputDialog("Digite la constraseña del  Desarrollador para entrar a esta area"+usu));
        if(usu==constraseña)
        {
              nuevos_usuarios ns= new nuevos_usuarios(this,true);
              ns.setVisible(true);
             //this.dispose();   
            
            
        
         
        }
        else
        {
            JOptionPane.showMessageDialog(null,"ERROR CONSTRASEÑA INVALIDA");
        }
        
    }//GEN-LAST:event_botonnuevousuarioActionPerformed

    private void conectorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_conectorActionPerformed
       Connection conexion =getConnection();
       PreparedStatement ps;
       ResultSet rs;
       try{
           ps=conexion.prepareStatement("select * from prueba");
           rs=ps.executeQuery();
           if(rs.next())
           {
               JOptionPane.showMessageDialog(null,"Nombre:"+rs.getString("nombre")+
                       "\nDomicilio:"+rs.getString("domicilio")+
                       "\n celular:"+rs.getString("celular")+
                        "\nCorreo Electronico:"+rs.getString("correo_electronico")+
                       "\nFecha de Nacimineto:"+String.valueOf(rs.getDate("fecha_nacimineto"))+
                       "\nGenero:"+rs.getString("genero"));
           }
           else 
           {
               JOptionPane.showMessageDialog(null,"no existe registros");
           }
           conexion.close();
           
       }catch(Exception ex)
       {
           System.err.println("Error , "+ex);
       }
       
    }//GEN-LAST:event_conectorActionPerformed
      public Connection getConnection()
      {
         Connection conexion=null;
         try{
             Class.forName("com.mysql.jdbc.Driver");
             conexion=(Connection) DriverManager.getConnection(url,usuario,Constrase);
             JOptionPane.showMessageDialog(null,"Conexion Existosa");
         }catch(Exception ex)
         {
             System.out.println("error  "+ex);
         }
         return conexion;
      }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boton;
    private javax.swing.JButton botoniniciar;
    private javax.swing.JButton botonnuevousuario;
    private javax.swing.JPasswordField cajaconstraseña;
    private javax.swing.JTextField cajausuario;
    private javax.swing.JButton conector;
    private javax.swing.JLabel etiquetaconstraseña;
    private javax.swing.JLabel etiquetalogin;
    private javax.swing.JLabel etiquetausuario;
    private javax.swing.JLabel imagenfondo;
    private javax.swing.JLabel imagenusuario;
    private javax.swing.JPanel panel;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent ae) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
