/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Login;

/**
 *
 * @author ricar
 */
public class nuevos_usuarios extends javax.swing.JDialog {
     static  nuevousuario ns2 ;
    /**
     * Creates new form nuevos_usuarios
     */
    public nuevos_usuarios(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        //this.setSize(800,50);
        this.setLocation(800,60);
        //this.setLocationRelativeTo(null);
        initComponents();
      
      
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        etiqueta_titulo = new javax.swing.JLabel();
        et_nombre = new javax.swing.JLabel();
        et_apellido = new javax.swing.JLabel();
        et_correo = new javax.swing.JLabel();
        cj_nombre = new javax.swing.JTextField();
        cj_apellido = new javax.swing.JTextField();
        cj_correo = new javax.swing.JTextField();
        et_telefono = new javax.swing.JLabel();
        et_constraseña = new javax.swing.JLabel();
        cj_telefono = new javax.swing.JTextField();
        cj_constraseña = new javax.swing.JPasswordField();
        et_datos = new javax.swing.JLabel();
        bt_guardar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 51, 102));

        etiqueta_titulo.setBackground(new java.awt.Color(51, 51, 51));
        etiqueta_titulo.setFont(new java.awt.Font("Arial", 3, 24)); // NOI18N
        etiqueta_titulo.setForeground(new java.awt.Color(255, 255, 255));
        etiqueta_titulo.setText("Nuevo Usuario");

        et_nombre.setBackground(new java.awt.Color(0, 0, 0));
        et_nombre.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        et_nombre.setForeground(new java.awt.Color(255, 255, 255));
        et_nombre.setText("Nombre:");

        et_apellido.setBackground(new java.awt.Color(0, 0, 0));
        et_apellido.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        et_apellido.setForeground(new java.awt.Color(255, 255, 255));
        et_apellido.setText("Apellido:");

        et_correo.setBackground(new java.awt.Color(0, 0, 0));
        et_correo.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        et_correo.setForeground(new java.awt.Color(255, 255, 255));
        et_correo.setText("Correo:");

        cj_nombre.setBackground(new java.awt.Color(0, 0, 0));
        cj_nombre.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        cj_nombre.setForeground(new java.awt.Color(255, 255, 255));
        cj_nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cj_nombreActionPerformed(evt);
            }
        });

        cj_apellido.setBackground(new java.awt.Color(0, 0, 0));
        cj_apellido.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        cj_apellido.setForeground(new java.awt.Color(255, 255, 255));

        cj_correo.setBackground(new java.awt.Color(0, 0, 0));
        cj_correo.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        cj_correo.setForeground(new java.awt.Color(255, 255, 255));

        et_telefono.setBackground(new java.awt.Color(0, 0, 0));
        et_telefono.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        et_telefono.setForeground(new java.awt.Color(255, 255, 255));
        et_telefono.setText("Telefono:");

        et_constraseña.setBackground(new java.awt.Color(0, 0, 0));
        et_constraseña.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        et_constraseña.setForeground(new java.awt.Color(255, 255, 255));
        et_constraseña.setText("Constraseña:");

        cj_telefono.setBackground(new java.awt.Color(0, 0, 0));
        cj_telefono.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        cj_telefono.setForeground(new java.awt.Color(255, 255, 255));

        cj_constraseña.setBackground(new java.awt.Color(0, 0, 0));
        cj_constraseña.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        cj_constraseña.setForeground(new java.awt.Color(255, 255, 255));
        cj_constraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cj_constraseñaActionPerformed(evt);
            }
        });

        et_datos.setBackground(new java.awt.Color(0, 0, 0));
        et_datos.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        et_datos.setForeground(new java.awt.Color(255, 255, 255));
        et_datos.setText("Ingrese Los Datos: ");

        bt_guardar.setBackground(new java.awt.Color(0, 0, 0));
        bt_guardar.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        bt_guardar.setForeground(new java.awt.Color(255, 255, 255));
        bt_guardar.setText("Guardar");
        bt_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_guardarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(et_telefono, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(et_nombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(et_apellido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(et_correo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(40, 40, 40)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(cj_nombre, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)
                                        .addComponent(cj_apellido)
                                        .addComponent(cj_telefono))
                                    .addComponent(cj_correo, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(et_constraseña)
                                .addGap(18, 18, 18)
                                .addComponent(cj_constraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(etiqueta_titulo)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(et_datos)))))
                .addContainerGap(10, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(bt_guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(etiqueta_titulo)
                .addGap(14, 14, 14)
                .addComponent(et_datos)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(et_nombre)
                    .addComponent(cj_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(et_apellido)
                    .addComponent(cj_apellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(et_correo)
                    .addComponent(cj_correo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(et_telefono)
                    .addComponent(cj_telefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(et_constraseña)
                    .addComponent(cj_constraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bt_guardar)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void cj_nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cj_nombreActionPerformed
         
        
   
        
        
        
        
    }//GEN-LAST:event_cj_nombreActionPerformed

    private void bt_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_guardarActionPerformed
        // TODO add your handling code here:
      
        String nombre=cj_nombre.getText();
        String apellido=cj_apellido.getText();
        String correo=cj_correo.getText();
        String telefono=cj_telefono.getText();
            String constraseña="";
            for(int n=0;n< cj_constraseña.getPassword().length; n++)
            {
                constraseña+=cj_constraseña.getPassword()[n];
             
            }
  
        ns2=new nuevousuario(nombre,apellido,correo,telefono,constraseña);
          System.out.println(nombre+" "+apellido+" "+correo+" "+telefono+" "+constraseña);
        
    
        this.dispose();
    }//GEN-LAST:event_bt_guardarActionPerformed

    private void cj_constraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cj_constraseñaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cj_constraseñaActionPerformed

    /**
     * @param args the command line arguments
     */
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(nuevos_usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(nuevos_usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(nuevos_usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(nuevos_usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                nuevos_usuarios dialog = new nuevos_usuarios(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_guardar;
    private javax.swing.JTextField cj_apellido;
    public javax.swing.JPasswordField cj_constraseña;
    private javax.swing.JTextField cj_correo;
    public javax.swing.JTextField cj_nombre;
    private javax.swing.JTextField cj_telefono;
    private javax.swing.JLabel et_apellido;
    private javax.swing.JLabel et_constraseña;
    private javax.swing.JLabel et_correo;
    private javax.swing.JLabel et_datos;
    private javax.swing.JLabel et_nombre;
    private javax.swing.JLabel et_telefono;
    private javax.swing.JLabel etiqueta_titulo;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
