/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventana;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ricar
 */
public class ventana extends javax.swing.JFrame {

   private DefaultComboBoxModel <Persona> modelo=new DefaultComboBoxModel <Persona>();
   private DefaultTableModel modelotabla=new DefaultTableModel();
    public ventana() {
        initComponents();
        llenandotabla();
        llenarcombobox();
        setLocationRelativeTo(null);
        
    }
    private void llenandotabla()
    {
        modelotabla.addColumn("Nombre");
        modelotabla.addColumn("Apellido");
        modelotabla.addColumn("Correo");
        modelotabla.addColumn("Celular");
        modelotabla.addColumn("Direccion");
    }
    private void llenarcombobox()
    {
        modelo.addElement(new Persona("Ricardo","Altamira","ricarhogmail.com","374774777","sol"));
        modelo.addElement(new Persona("Roky","Altamira","ricarhogmail.com","374774777","sol"));
        modelo.addElement(new Persona("poo","Altamira","ricarhogmail.com","37477","sol"));
        modelo.addElement(new Persona("fernando","Altamira","ricarhogmail.com","374774777","sol"));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JPanel();
        etiquetapersona = new javax.swing.JLabel();
        Insertarpersona = new javax.swing.JButton();
        combopersona = new javax.swing.JComboBox<>();
        scrolltabla = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        ListSelectionListener oyentedeselecion=new ListSelectionListener()
        {
            @Override
            public void  valueChanged(ListSelectionEvent e)
            {
                if(e.getValueIsAdjusting())
                {
                    int filaselecionada=tabla.getSelectedRow();
                    String nombre=(String) modelotabla.getValueAt(filaselecionada, 0);
                    String apellido=(String) modelotabla.getValueAt(filaselecionada, 1);
                    String email=(String) modelotabla.getValueAt(filaselecionada, 2);
                    String celular=(String) modelotabla.getValueAt(filaselecionada, 3);
                    String direccion=(String) modelotabla.getValueAt(filaselecionada, 4);
                    cajanombre.setText(nombre);
                    cajaapellidos.setText(apellido);
                    cajaemail.setText(celular);
                    cajacelular.setText(celular);
                    cajadireccion.setText(direccion);

                }

            }

        };

        tabla.getSelectionModel().addListSelectionListener(oyentedeselecion);
        separador = new javax.swing.JSeparator();
        etiquetanombre = new javax.swing.JLabel();
        cajanombre = new javax.swing.JTextField();
        etiquetadatospersona = new javax.swing.JLabel();
        etiquetaapellidos = new javax.swing.JLabel();
        cajaapellidos = new javax.swing.JTextField();
        etiquetaemail = new javax.swing.JLabel();
        cajaemail = new javax.swing.JTextField();
        etiquetacelular = new javax.swing.JLabel();
        cajacelular = new javax.swing.JTextField();
        etiquetadireccion = new javax.swing.JLabel();
        cajadireccion = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        etiquetapersona.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        etiquetapersona.setText("persona");

        Insertarpersona.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Insertarpersona.setText("Insertar persona");
        Insertarpersona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InsertarpersonaActionPerformed(evt);
            }
        });

        combopersona.setModel(modelo);
        combopersona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combopersonaActionPerformed(evt);
            }
        });

        tabla.setModel(modelotabla);
        scrolltabla.setViewportView(tabla);

        etiquetanombre.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        etiquetanombre.setText("Nombre");

        cajanombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cajanombreActionPerformed(evt);
            }
        });

        etiquetadatospersona.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        etiquetadatospersona.setText("Datos persona");

        etiquetaapellidos.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        etiquetaapellidos.setText("Apellidos");

        etiquetaemail.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        etiquetaemail.setText("Email");

        cajaemail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cajaemailActionPerformed(evt);
            }
        });

        etiquetacelular.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        etiquetacelular.setText("Celular");

        etiquetadireccion.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        etiquetadireccion.setText("Direccion");

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(separador, javax.swing.GroupLayout.PREFERRED_SIZE, 443, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(etiquetadatospersona, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(scrolltabla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(etiquetapersona, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(panelLayout.createSequentialGroup()
                                            .addComponent(combopersona, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(57, 57, 57)
                                            .addComponent(Insertarpersona)))))))
                    .addGroup(panelLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(etiquetanombre))
                    .addGroup(panelLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cajadireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelLayout.createSequentialGroup()
                                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(etiquetadireccion)
                                    .addComponent(etiquetaemail, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cajanombre)
                                    .addComponent(cajaemail, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE))
                                .addGap(82, 82, 82)
                                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cajacelular, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(etiquetacelular, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cajaapellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(etiquetaapellidos))))))
                .addContainerGap(124, Short.MAX_VALUE))
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(etiquetapersona)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Insertarpersona)
                    .addComponent(combopersona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(scrolltabla, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(separador, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(etiquetadatospersona)
                .addGap(18, 18, 18)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiquetanombre)
                    .addComponent(etiquetaapellidos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cajanombre, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cajaapellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiquetaemail)
                    .addComponent(etiquetacelular))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cajacelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cajaemail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(etiquetadireccion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cajadireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cajanombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cajanombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cajanombreActionPerformed

    private void cajaemailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cajaemailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cajaemailActionPerformed

    private void combopersonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combopersonaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combopersonaActionPerformed

    private void InsertarpersonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InsertarpersonaActionPerformed
        // TODO add your handling code here:
        Persona p= (Persona)combopersona.getSelectedItem();
        String nombres=p.getNombre();
        String apellidos=p.getApellido();
        String email=p.getEmail();
        String celular=p.getCelular();
        String direccion=p.getDireccion();
        String[]persona={nombres,apellidos,email,celular,direccion};
        modelotabla.addRow(persona);
    }//GEN-LAST:event_InsertarpersonaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws ClassNotFoundException {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

       /* Create and display the form */     //           try {
     /*      UIManager.setLookAndFeel("com.jtatto.plaf.bernstein.BernsteinLookAndFeel");
       } catch (InstantiationException ex) {
           //Logger.getLogger(ventana.class.getName()).log(Level.SEVERE, null, ex);
       } catch (IllegalAccessException ex) {
           //Logger.getLogger(ventana.class.getName()).log(Level.SEVERE, null, ex);
       } catch (UnsupportedLookAndFeelException ex) {
           //Logger.getLogger(ventana.class.getName()).log(Level.SEVERE, null, ex);
       }*/
   
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ventana().setVisible(true);
            }
        });

    
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Insertarpersona;
    private javax.swing.JTextField cajaapellidos;
    private javax.swing.JTextField cajacelular;
    private javax.swing.JTextField cajadireccion;
    private javax.swing.JTextField cajaemail;
    private javax.swing.JTextField cajanombre;
    private javax.swing.JComboBox<Persona> combopersona;
    private javax.swing.JLabel etiquetaapellidos;
    private javax.swing.JLabel etiquetacelular;
    private javax.swing.JLabel etiquetadatospersona;
    private javax.swing.JLabel etiquetadireccion;
    private javax.swing.JLabel etiquetaemail;
    private javax.swing.JLabel etiquetanombre;
    private javax.swing.JLabel etiquetapersona;
    private javax.swing.JPanel panel;
    private javax.swing.JScrollPane scrolltabla;
    private javax.swing.JSeparator separador;
    private javax.swing.JTable tabla;
    // End of variables declaration//GEN-END:variables
}
