/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Programa;

import Modelo.Conexion;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author ricar
 */
public class Ventana extends javax.swing.JFrame {

    /**
     * Creates new form Ventana
     */
    public Ventana() {
        initComponents();
        radio_grupos.add(radio_hombre);
         radio_grupos.add(radio_mujer);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        radio_grupos = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        spin_edad = new javax.swing.JSpinner();
        casilla_fut = new javax.swing.JCheckBox();
        casilla_bas = new javax.swing.JCheckBox();
        casilla_ten = new javax.swing.JCheckBox();
        casilla_natacion = new javax.swing.JCheckBox();
        casilla_bei = new javax.swing.JCheckBox();
        jLabel4 = new javax.swing.JLabel();
        radio_hombre = new javax.swing.JRadioButton();
        radio_mujer = new javax.swing.JRadioButton();
        boton_insertar = new javax.swing.JButton();
        boton_mostrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        jLabel1.setText("Formulario:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, 103, 45));

        jLabel2.setText("Seleccione genero");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 121, -1));

        jLabel3.setText("Cual es tu edad");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 90, 20));
        getContentPane().add(spin_edad, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, 70, -1));

        casilla_fut.setText("Futbol");
        casilla_fut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                casilla_futActionPerformed(evt);
            }
        });
        getContentPane().add(casilla_fut, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, -1, -1));

        casilla_bas.setText("Basquet");
        casilla_bas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                casilla_basActionPerformed(evt);
            }
        });
        getContentPane().add(casilla_bas, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, -1, -1));

        casilla_ten.setText("Tennis");
        getContentPane().add(casilla_ten, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, -1, -1));

        casilla_natacion.setText("Natacion");
        getContentPane().add(casilla_natacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, -1, -1));

        casilla_bei.setText("Beisbol");
        getContentPane().add(casilla_bei, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, -1, -1));

        jLabel4.setText("Seleccione su deporte favorito");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 210, 20));

        radio_hombre.setText("Hombre");
        radio_hombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio_hombreActionPerformed(evt);
            }
        });
        getContentPane().add(radio_hombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        radio_mujer.setText("Mujer");
        getContentPane().add(radio_mujer, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        boton_insertar.setText("Insertar registro");
        boton_insertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_insertarActionPerformed(evt);
            }
        });
        getContentPane().add(boton_insertar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, 130, -1));

        boton_mostrar.setText("Mostrar Registros");
        boton_mostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_mostrarActionPerformed(evt);
            }
        });
        getContentPane().add(boton_mostrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 380, 130, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void casilla_futActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_casilla_futActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_casilla_futActionPerformed

    private void casilla_basActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_casilla_basActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_casilla_basActionPerformed

    private void boton_insertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_insertarActionPerformed
               Conexion con=new Conexion();
               PreparedStatement ps=null;
               String genero="";
               int edad=0;
               boolean futbol=false,basquet=false,tennis=false,natacion=false,beisbol=false;
               //radio botones jRadioButton
               
               if(radio_hombre.isSelected()==true){
                   genero="Hombre";
               }
               else if(radio_mujer.isSelected() ==true){
                   genero="Mujer";
               }
               //edad obtenemos la edad JSpinner
               edad=(int) spin_edad.getValue();
               //Casillas de verificacion -Jcheckbox
               if(casilla_fut.isSelected()==true){
                   futbol=true;
               }
               if(casilla_bas.isSelected()==true)
               {
                   basquet=true;
               }
               if(casilla_ten.isSelected()==true){
                   tennis=true;
               }
               if(casilla_natacion.isSelected()==true){
                   natacion=true;
               }
               if(casilla_bei.isSelected()==true)
               {
                   beisbol=true;
               }
               
               
             
               
               try{
                   
                   Connection conexion=con.getConexion();
                     ps=conexion.prepareStatement("insert into Gustos (genero,edad,futbol,basque,tenis,natacion,beisbol) values( ?,?,?,?,?,?,?)");
                   ps.setString(1, genero);
                   ps.setInt(2, edad);
                   ps.setBoolean(3,futbol);
                   ps.setBoolean(4,basquet);
                   ps.setBoolean(5,tennis);
                   ps.setBoolean(6,natacion);
                   ps.setBoolean(7,beisbol);
                   ps.executeUpdate();
                   conexion.close();
                   JOptionPane.showMessageDialog(null,"Registro insertado");
                   
                   
                   
               }catch(Exception ex){
                   System.err.println("Error ,"+ex);
               }
               
               
    }//GEN-LAST:event_boton_insertarActionPerformed

    private void boton_mostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_mostrarActionPerformed
       Conexion con=new Conexion();
       PreparedStatement ps=null;
       ResultSet rs=null;
       try{
           Connection conexion=con.getConexion();
           ps=conexion.prepareStatement("Select genero,edad,futbol,basque,tenis,natacion,beisbol from gustos where codigo=?");
           ps.setInt(1,1);
           rs=ps.executeQuery();
           while(rs.next()){
               //radio botones
               if(rs.getString("genero").equals("Hombre")){
                 radio_hombre.setSelected(true);
               }
               else if(rs.getString("genero").equals("Mujer")){
                   radio_mujer.setSelected(true);
               }
               //spiner
               spin_edad.setValue(rs.getInt("edad"));
               //casillas de verificacion
               if(rs.getBoolean("futbol")==true)
               {
                   casilla_fut.setSelected(true);
               }
               if(rs.getBoolean("basque")==true)
               {
                   casilla_bas.setSelected(true);
               }
               if(rs.getBoolean("tenis")==true)
               {
                   casilla_ten.setSelected(true);
               }
               if(rs.getBoolean("natacion")==true){
                   casilla_natacion.setSelected(true);
               }
               if(rs.getBoolean("beisbol")==true){
                   casilla_bei.setSelected(true);
               }
               
           }
           
           
           
           
           
           conexion.close();
           
       }catch(Exception ex){
           System.err.println("Error ,"+ex);
       }
       
    }//GEN-LAST:event_boton_mostrarActionPerformed

    private void radio_hombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio_hombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radio_hombreActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boton_insertar;
    private javax.swing.JButton boton_mostrar;
    private javax.swing.JCheckBox casilla_bas;
    private javax.swing.JCheckBox casilla_bei;
    private javax.swing.JCheckBox casilla_fut;
    private javax.swing.JCheckBox casilla_natacion;
    private javax.swing.JCheckBox casilla_ten;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.ButtonGroup radio_grupos;
    private javax.swing.JRadioButton radio_hombre;
    private javax.swing.JRadioButton radio_mujer;
    private javax.swing.JSpinner spin_edad;
    // End of variables declaration//GEN-END:variables
}
