/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package BD_JTABLE;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ricar
 */
public class Ventana extends javax.swing.JFrame {
          PreparedStatement ps=null;
           ResultSet rs=null; 
   
   
    /**
     * Creates new form Ventana
     */
    public Ventana() {
        
        initComponents();
        this.setTitle("Mostrando lista de base de datos");
            this.setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabla_producto = new javax.swing.JTable();
        boton_mostrar = new javax.swing.JButton();
        etiqueta_codigo = new javax.swing.JLabel();
        caja_busqueda = new javax.swing.JTextField();
        etiqueta_clave = new javax.swing.JLabel();
        etiqueta_nombre = new javax.swing.JLabel();
        etiqueta_cantidad = new javax.swing.JLabel();
        etiqueta_costo = new javax.swing.JLabel();
        caja_clave = new javax.swing.JTextField();
        caja_nombre = new javax.swing.JTextField();
        caja_cantidad = new javax.swing.JTextField();
        caja_costo = new javax.swing.JTextField();
        boton_insertar = new javax.swing.JButton();
        boton_modificar = new javax.swing.JButton();
        boton_eliminar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabla_producto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Clave", "Nombre", "Cantidad", "Costo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Float.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabla_producto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabla_productoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabla_producto);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 108, -1, 283));

        boton_mostrar.setText("Mostrar Datos BD");
        boton_mostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_mostrarActionPerformed(evt);
            }
        });
        getContentPane().add(boton_mostrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(283, 58, -1, -1));

        etiqueta_codigo.setBackground(new java.awt.Color(0, 255, 0));
        etiqueta_codigo.setForeground(new java.awt.Color(153, 153, 0));
        etiqueta_codigo.setText("Codigo");
        getContentPane().add(etiqueta_codigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 65, 50, 19));
        getContentPane().add(caja_busqueda, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 62, 151, -1));

        etiqueta_clave.setText("Clave:");
        getContentPane().add(etiqueta_clave, new org.netbeans.lib.awtextra.AbsoluteConstraints(525, 108, -1, -1));

        etiqueta_nombre.setText("Nombre:");
        getContentPane().add(etiqueta_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(525, 167, -1, -1));

        etiqueta_cantidad.setText("Cantidad:");
        getContentPane().add(etiqueta_cantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(525, 224, -1, -1));

        etiqueta_costo.setText("Costo:");
        getContentPane().add(etiqueta_costo, new org.netbeans.lib.awtextra.AbsoluteConstraints(525, 285, 53, -1));
        getContentPane().add(caja_clave, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 100, 130, -1));
        getContentPane().add(caja_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 160, 130, -1));
        getContentPane().add(caja_cantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 220, 140, -1));
        getContentPane().add(caja_costo, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 280, 140, -1));

        boton_insertar.setText("Insertar");
        boton_insertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_insertarActionPerformed(evt);
            }
        });
        getContentPane().add(boton_insertar, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 350, -1, -1));

        boton_modificar.setText("Modificar");
        boton_modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_modificarActionPerformed(evt);
            }
        });
        getContentPane().add(boton_modificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 350, -1, -1));

        boton_eliminar.setText("Eliminar");
        boton_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_eliminarActionPerformed(evt);
            }
        });
        getContentPane().add(boton_eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 350, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void boton_mostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_mostrarActionPerformed
       
      
        
        DefaultTableModel modelotabla=new DefaultTableModel();
        tabla_producto.setModel(modelotabla);
       String campo=caja_busqueda.getText();
       String where="";
       if(!"".equals(campo))
       {
           where="where clave =  "+campo+"";
           
       }
     
   
      try{
          
          Conexion_BD_JTABLE con=new Conexion_BD_JTABLE();
          Connection conexion=con.getConexion();
          ps=conexion.prepareStatement("select clave,nombre,cantidad,costo from Producto "+where);
          rs=ps.executeQuery();
          modelotabla.addColumn("Clave");
          modelotabla.addColumn("Nombre");
          modelotabla.addColumn("Cantidad");
          modelotabla.addColumn("Costo");
       int ancho []={50,150,50,70};
      for(int i=0; i<4; i++)
      {
          tabla_producto.getColumnModel().getColumn(i).setPreferredWidth(ancho[i]);
      }
          
          while(rs.next()){
              Object fila[]=new Object[4];
              for(int n=0; n<4; n++)
              {
                  fila[n]=rs.getObject(n+1);
              }
              modelotabla.addRow(fila);
          }
          
      }catch(Exception ex){
        System.err.println("Error ,"+ex);  
      }
        
          
      
    }//GEN-LAST:event_boton_mostrarActionPerformed

    private void tabla_productoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabla_productoMouseClicked
        
        
        try{
          Conexion_BD_JTABLE con=new Conexion_BD_JTABLE();
          Connection conexion=con.getConexion();
          int fila=tabla_producto.getSelectedRow();
          String clave=tabla_producto.getValueAt(fila, 0).toString();
          ps=conexion.prepareStatement("select clave,nombre,cantidad,costo from Producto where clave=?");
          ps.setString(1,clave);
          rs=ps.executeQuery();
          
          while(rs.next())
          {
              caja_clave.setText(rs.getString("clave"));
              caja_nombre.setText(rs.getString("nombre"));
              caja_cantidad.setText(String.valueOf(rs.getInt("cantidad")));
              caja_costo.setText(String.valueOf(rs.getFloat("costo")));
              
          }
          
          
        }catch(Exception ex){
            System.err.println("Error ,"+ex);
        }
        
        
        
    }//GEN-LAST:event_tabla_productoMouseClicked

    private void boton_modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_modificarActionPerformed
       PreparedStatement ps=null;
        try{
            Conexion_BD_JTABLE con=new Conexion_BD_JTABLE();
            Connection conexion=con.getConexion();
            ps=conexion.prepareStatement("update Producto set clave=?,nombre=?,cantidad=?,costo=? where clave=? ");
            ps.setString(1,caja_clave.getText());
            ps.setString(2,caja_nombre.getText());
            ps.setInt(3,Integer.parseInt(caja_cantidad.getText()));
            ps.setDouble(4,Double.parseDouble(caja_costo.getText()));
            ps.setString(5,caja_clave.getText());
            ps.executeUpdate();
            JOptionPane.showMessageDialog(null,"Registro modificado ");
                      
            
        }catch(Exception ex){
            System.err.println("Error ,"+ex);
            
        }
    }//GEN-LAST:event_boton_modificarActionPerformed

    private void boton_insertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_insertarActionPerformed
        PreparedStatement ps=null;
        try{
            Conexion_BD_JTABLE con=new Conexion_BD_JTABLE();
            Connection conexion=con.getConexion();
            ps=conexion.prepareStatement("insert into  Producto(clave,nombre,cantidad,costo) values(?,?,?,?)  ");
            ps.setString(1,caja_clave.getText());
            ps.setString(2,caja_nombre.getText());
            ps.setInt(3,Integer.parseInt(caja_cantidad.getText()));
            ps.setDouble(4,Double.parseDouble(caja_costo.getText()));
            ps.executeUpdate();
            JOptionPane.showMessageDialog(null,"Ingresado registro");
          
            
        }catch(Exception ex){
            System.err.println("Error ,"+ex);
            
        }
    }//GEN-LAST:event_boton_insertarActionPerformed

    private void boton_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_eliminarActionPerformed
         PreparedStatement ps=null;
        try{
            Conexion_BD_JTABLE con=new Conexion_BD_JTABLE();
            Connection conexion=con.getConexion();
            ps=conexion.prepareStatement("delete from Producto  where clave=? ");
            ps.setString(1,caja_clave.getText());
            ps.executeUpdate();
            JOptionPane.showMessageDialog(null,"Registro eliminado ");
                      
            
        }catch(Exception ex){
            System.err.println("Error ,"+ex);
            
        }
    }//GEN-LAST:event_boton_eliminarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boton_eliminar;
    private javax.swing.JButton boton_insertar;
    private javax.swing.JButton boton_modificar;
    private javax.swing.JButton boton_mostrar;
    private javax.swing.JTextField caja_busqueda;
    private javax.swing.JTextField caja_cantidad;
    private javax.swing.JTextField caja_clave;
    private javax.swing.JTextField caja_costo;
    private javax.swing.JTextField caja_nombre;
    private javax.swing.JLabel etiqueta_cantidad;
    private javax.swing.JLabel etiqueta_clave;
    private javax.swing.JLabel etiqueta_codigo;
    private javax.swing.JLabel etiqueta_costo;
    private javax.swing.JLabel etiqueta_nombre;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabla_producto;
    // End of variables declaration//GEN-END:variables
}
