/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Programa;

import Modelo.Conexion;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author ricar
 */
public class Ventana extends javax.swing.JFrame {

    /**
     * Creates new form Ventana
     */
    public Ventana() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        Seleccionar_fecha = new com.toedter.calendar.JDateChooser();
        boton_mostrarfecha = new javax.swing.JButton();
        boton_Insertar = new javax.swing.JButton();
        boton_cargar = new javax.swing.JButton();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        boton_mostrarfecha.setText("Mostrar fecha");
        boton_mostrarfecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_mostrarfechaActionPerformed(evt);
            }
        });

        boton_Insertar.setText("Insertar fecha");
        boton_Insertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_InsertarActionPerformed(evt);
            }
        });

        boton_cargar.setText("Cargar_fecha");
        boton_cargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_cargarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(boton_mostrarfecha)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(boton_cargar, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Seleccionar_fecha, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(boton_Insertar, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(54, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Seleccionar_fecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(boton_Insertar))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(boton_mostrarfecha)
                    .addComponent(boton_cargar))
                .addContainerGap(183, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void boton_mostrarfechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_mostrarfechaActionPerformed
        Date date=Seleccionar_fecha.getDate();
        long d=date.getTime();
        java.sql.Date fecha=new java.sql.Date(d);
        JOptionPane.showMessageDialog(null,fecha);
    }//GEN-LAST:event_boton_mostrarfechaActionPerformed

    private void boton_InsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_InsertarActionPerformed
        Conexion con=new Conexion();
        PreparedStatement ps=null;
        try{
            Connection conexion=con.getConexion();
            ps=conexion.prepareStatement("insert into tiempo (fecha) values (?)");
                 Date date=Seleccionar_fecha.getDate();
        long d=date.getTime();
        java.sql.Date fecha=new java.sql.Date(d);
            ps.setDate(1,fecha);
            ps.executeUpdate();
              JOptionPane.showMessageDialog(null,"Fecha insertada correctamente");
            conexion.close();
            
        }catch(Exception ex){
            System.out.println("Error ,"+ex);
        }
                
    }//GEN-LAST:event_boton_InsertarActionPerformed

    private void boton_cargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_cargarActionPerformed
       Conexion con=new Conexion();
        PreparedStatement ps=null;
        ResultSet rs=null;
        try{
            Connection conexion=con.getConexion();
            ps=conexion.prepareStatement("select fecha from tiempo where id_tiempo=?");
          
            ps.setInt(1,1);
            rs=ps.executeQuery();
            while(rs.next()){
                Seleccionar_fecha.setDate(rs.getDate("fecha"));
                
            }
              JOptionPane.showMessageDialog(null,"Fecha insertada correctamente");
            conexion.close();
            
        }catch(Exception ex){
            System.out.println("Error ,"+ex);
        }
    }//GEN-LAST:event_boton_cargarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser Seleccionar_fecha;
    private javax.swing.JButton boton_Insertar;
    private javax.swing.JButton boton_cargar;
    private javax.swing.JButton boton_mostrarfecha;
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables
}
