/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

/**
 *
 * @author ricar
 */
public class Vista extends javax.swing.JFrame {

    /**
     * Creates new form Vista
     */
    public Vista() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        et_clave = new javax.swing.JLabel();
        et_nombre = new javax.swing.JLabel();
        et_domicilio = new javax.swing.JLabel();
        et_celular = new javax.swing.JLabel();
        et_correoelectronico = new javax.swing.JLabel();
        et_fechadenacimiento = new javax.swing.JLabel();
        caja_clave = new javax.swing.JTextField();
        caja_nombre = new javax.swing.JTextField();
        caja_domicilio = new javax.swing.JTextField();
        caja_celular = new javax.swing.JTextField();
        caja_correo = new javax.swing.JTextField();
        caja_fechadn = new javax.swing.JTextField();
        et_genero = new javax.swing.JLabel();
        combo_genero = new javax.swing.JComboBox<>();
        boton_buscar = new javax.swing.JButton();
        caja_buscar = new javax.swing.JTextField();
        idpersona = new javax.swing.JTextField();
        boton_insertar = new javax.swing.JButton();
        boton_modificar = new javax.swing.JButton();
        boton_eliminar = new javax.swing.JButton();
        boton_limpiar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        et_clave.setText("Clave:");
        getContentPane().add(et_clave, new org.netbeans.lib.awtextra.AbsoluteConstraints(123, 45, 58, -1));

        et_nombre.setText("Nombre:");
        getContentPane().add(et_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(123, 78, 58, -1));

        et_domicilio.setText("Domicilio:");
        getContentPane().add(et_domicilio, new org.netbeans.lib.awtextra.AbsoluteConstraints(123, 120, 58, -1));

        et_celular.setText("Celular:");
        getContentPane().add(et_celular, new org.netbeans.lib.awtextra.AbsoluteConstraints(123, 162, -1, -1));

        et_correoelectronico.setText("Correo Electronico:");
        getContentPane().add(et_correoelectronico, new org.netbeans.lib.awtextra.AbsoluteConstraints(123, 205, 120, -1));

        et_fechadenacimiento.setText("Fecha de nacimiento:");
        getContentPane().add(et_fechadenacimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(123, 263, -1, -1));
        getContentPane().add(caja_clave, new org.netbeans.lib.awtextra.AbsoluteConstraints(199, 41, 86, -1));
        getContentPane().add(caja_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(199, 74, 199, -1));
        getContentPane().add(caja_domicilio, new org.netbeans.lib.awtextra.AbsoluteConstraints(199, 116, 199, -1));
        getContentPane().add(caja_celular, new org.netbeans.lib.awtextra.AbsoluteConstraints(199, 158, 185, -1));
        getContentPane().add(caja_correo, new org.netbeans.lib.awtextra.AbsoluteConstraints(249, 201, 150, -1));

        caja_fechadn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caja_fechadnActionPerformed(evt);
            }
        });
        getContentPane().add(caja_fechadn, new org.netbeans.lib.awtextra.AbsoluteConstraints(249, 255, 150, -1));

        et_genero.setText("Genero:");
        getContentPane().add(et_genero, new org.netbeans.lib.awtextra.AbsoluteConstraints(132, 314, 53, -1));

        combo_genero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "Masculino", "Femenino" }));
        getContentPane().add(combo_genero, new org.netbeans.lib.awtextra.AbsoluteConstraints(203, 309, 123, -1));

        boton_buscar.setText("Buscar");
        getContentPane().add(boton_buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 10, -1, -1));
        getContentPane().add(caja_buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 60, 60, -1));
        getContentPane().add(idpersona, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 130, -1));

        boton_insertar.setText("Insertar");
        getContentPane().add(boton_insertar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, 100, -1));

        boton_modificar.setText("Modificar");
        getContentPane().add(boton_modificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 360, 100, -1));

        boton_eliminar.setText("Eliminar");
        getContentPane().add(boton_eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 360, 90, -1));

        boton_limpiar.setText("Limpiar");
        boton_limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_limpiarActionPerformed(evt);
            }
        });
        getContentPane().add(boton_limpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 360, 90, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void caja_fechadnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caja_fechadnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_caja_fechadnActionPerformed

    private void boton_limpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_limpiarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boton_limpiarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton boton_buscar;
    public javax.swing.JButton boton_eliminar;
    public javax.swing.JButton boton_insertar;
    public javax.swing.JButton boton_limpiar;
    public javax.swing.JButton boton_modificar;
    public javax.swing.JTextField caja_buscar;
    public javax.swing.JTextField caja_celular;
    public javax.swing.JTextField caja_clave;
    public javax.swing.JTextField caja_correo;
    public javax.swing.JTextField caja_domicilio;
    public javax.swing.JTextField caja_fechadn;
    public javax.swing.JTextField caja_nombre;
    public javax.swing.JComboBox<String> combo_genero;
    private javax.swing.JLabel et_celular;
    private javax.swing.JLabel et_clave;
    private javax.swing.JLabel et_correoelectronico;
    private javax.swing.JLabel et_domicilio;
    private javax.swing.JLabel et_fechadenacimiento;
    private javax.swing.JLabel et_genero;
    private javax.swing.JLabel et_nombre;
    public javax.swing.JTextField idpersona;
    // End of variables declaration//GEN-END:variables
}
