/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Modelo.Usuario;

/**
 *
 * @author ricar
 */
public class Programa extends javax.swing.JFrame {
      Usuario usuario;//para asignacion de privilegios
    public Programa() {
        initComponents();
    }
    public  Programa(Usuario usuario){//creamos otro constructor para asignar privilegios
        initComponents();
        this.setLocationRelativeTo(null);
        this.usuario=usuario;
        etiqueta_nombre_programa.setText(usuario.getNombre());
        etiqueta_rol.setText(usuario.getRolusuario());
        if(usuario.getIdtipo_usuario()==1){
            
        }else if(usuario.getIdtipo_usuario()==2){//es para restringir a los usuarios comunes
            menu_provedores.setVisible(false);
            submenu_agregarproducto.setVisible(false);
            
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        etiqueta_nombre_programa = new javax.swing.JLabel();
        etiqueta_rol = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menu_productos = new javax.swing.JMenu();
        submenu_agregarproducto = new javax.swing.JMenuItem();
        submenu_modificarproducto = new javax.swing.JMenuItem();
        submenu_catalogoproductos = new javax.swing.JMenuItem();
        menu_provedores = new javax.swing.JMenu();
        submenu_agregarprovedor = new javax.swing.JMenuItem();
        submenu_catalogoprovedores = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel1.setText("Bienvenido al programa");

        menu_productos.setText("Productos");

        submenu_agregarproducto.setText("Agregar producto");
        menu_productos.add(submenu_agregarproducto);

        submenu_modificarproducto.setText("Modificar producto");
        menu_productos.add(submenu_modificarproducto);

        submenu_catalogoproductos.setText("catalogo productos");
        submenu_catalogoproductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submenu_catalogoproductosActionPerformed(evt);
            }
        });
        menu_productos.add(submenu_catalogoproductos);

        jMenuBar1.add(menu_productos);

        menu_provedores.setText("Provedores");

        submenu_agregarprovedor.setText("agregar provedor");
        menu_provedores.add(submenu_agregarprovedor);

        submenu_catalogoprovedores.setText("catalogo provedores");
        menu_provedores.add(submenu_catalogoprovedores);

        jMenuBar1.add(menu_provedores);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(etiqueta_nombre_programa, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(etiqueta_rol, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(120, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(91, 91, 91)
                .addComponent(etiqueta_nombre_programa, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(etiqueta_rol, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(144, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void submenu_catalogoproductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submenu_catalogoproductosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_submenu_catalogoproductosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Programa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Programa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Programa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Programa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Programa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel etiqueta_nombre_programa;
    private javax.swing.JLabel etiqueta_rol;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu menu_productos;
    private javax.swing.JMenu menu_provedores;
    private javax.swing.JMenuItem submenu_agregarproducto;
    private javax.swing.JMenuItem submenu_agregarprovedor;
    private javax.swing.JMenuItem submenu_catalogoproductos;
    private javax.swing.JMenuItem submenu_catalogoprovedores;
    private javax.swing.JMenuItem submenu_modificarproducto;
    // End of variables declaration//GEN-END:variables
}
